server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

open-api:
  kakao:
    url: https://dapi.kakao.com/v2/search/blog
    api-key: KakaoAK 383d35930fb99d8d14ff9eb70177444f
  Naver:
    url: https://openapi.naver.com/v1/search/blog.json
    X-Naver-Client-Id: 1mZHo66nce25UyYq7yDh
    X-Naver-Client-Secret: HNA7wdjufb

spring:
  #H2 DB Connection Settings
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  #  JPA Settings
  jpa:
    database: h2
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
