server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

open-api:
  kakao:
    url: https://dapi.kakao.com/v2/search/blog
    api-key: KakaoAK 383d35930fb99d8d14ff9eb70177444f
  Naver:
    url: https://openapi.naver.com/v1/search/blog.json
    X-Naver-Client-Id: 1mZHo66nce25UyYq7yDh
    X-Naver-Client-Secret: HNA7wdjufb