server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

open-api:
  kakao:
    url: https://dapi.kakao.com/v2/search/blog
    key: KakaoAK 383d35930fb99d8d14ff9eb70177444f
  naver:
    url: https://openapi.naver.com/v1/search/blog.json
    client-id: 1mZHo66nce25UyYq7yDh
    secret: HNA7wdjufb